/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    GlobalToast: typeof import('./src/components/GlobalToast.vue')['default']
    PpLayerEditor: typeof import('./src/components/map/PpLayerEditor.vue')['default']
    PpMapView: typeof import('./src/components/map/PpMapView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
    UserMenu: typeof import('./src/components/layout/UserMenu.vue')['default']
  }
}
